// Embeds a docker-compose.yml verbatim into src/pages/composeFile.generated.ts, so the Docker Compose
// page shows the real file instead of a retyped copy. Run it again whenever that file changes:
//
//   node --experimental-strip-types scripts/sync-compose.ts <path to deploy/docker-compose.yml>
import { readFileSync, writeFileSync } from 'node:fs'

const sourcePath = process.argv[2]
if (!sourcePath) {
  console.error('usage: node --experimental-strip-types scripts/sync-compose.ts <path to docker-compose.yml>')
  process.exit(1)
}

const content = readFileSync(sourcePath, 'utf8').replace(/\n+$/, '')
const outputPath = new URL('../src/pages/composeFile.generated.ts', import.meta.url)
const header = `// Generated by scripts/sync-compose.ts from deploy/docker-compose.yml. Do not edit by hand.\n`
writeFileSync(outputPath, `${header}export const composeFile = ${JSON.stringify(content)}\n`)
console.log(`wrote ${outputPath.pathname} from ${sourcePath}`)
